### ISSUE TITLE
How to run HelloWorld example？

### ISSUE THREAD

**Issue by Hep-dog** [klemenv/PyDevice#14]
Dear All,
I'm a newbie to EPICS.  I don't know how to run the HelloWorld example, i.e. how to process the following record after the PyDevice installation. I will be very grateful if there is a demo example or more detailed descriptions. Thanks in advance!

    record(longout, "PyDev:Test:HelloWorld") {
        field(DTYP, "pydev")
        field(OUT,  "@print('Hello world!')")
    }

Best regards,
Jiyizi

**Comment by klemenv** [comment]
Hi Jiyizi,

these are the rough steps to get the demo IOC running from beginning:
* download and compile EPICS base from https://epics.anl.gov/download/base/index.php
* download PyDevice from this repo, ideally using one of the tagged versions like https://github.com/klemenv/PyDevice/releases/tag/R1.1.1
* point PyDevice to your EPICS base folder by creating configure/RELEASE.local file with a single line, ie. `echo EPICS_BASE=/ics/epics/7.0.6.1/base > configure/RELEASE.local`
* compile PyDevice with `make`
* `cd iocBoot/iocpydev/`
* start the IOC with `./st.cmd`

**Comment by vstadnytskyi-FDA** [comment]
Can I run this example and create my own CA server without installing EPICS base?

**Comment by klemenv** [comment]
Hi Valentyn,

the ticket has been closed, but hopefully this reply gets to you.

PyDevice requires EPICS base and will not run without it. You could try
compiling it statically and get static binary without dynamic library
dependencies on EPICS, but you'll need EPICS base to compile it at the very
least.

As for Windows 10, I don't have experience with that, I know EPICS base
will compile there and with little help PyDevice should too, but I don't
have a Windows 10 system for me to do that. Patches and merge requests are
welcome though.

-- Klemen
