### ISSUE TITLE
Do I need EPICS base for this library to work?

### ISSUE THREAD

**Issue by vstadnytskyi-FDA** [klemenv/PyDevice#16]
- Can I run this example and create my own CA server without installing EPICS base?
- Also can I install EPICS base on windows 10?

**Comment by klemenv** [comment]
Hi Valentyn,

PyDevice requires EPICS base and will not run compile or run without it. It's just a device support, leveraging all EPICS DB and CA to the base itself. You could try compiling PyDevice statically and get static binary without dynamic library
dependencies on EPICS, but you'll need EPICS base to compile it at the very least.

As for Windows 10, I don't have experience with that, I know EPICS base will compile there and with little help PyDevice should too, but I don't have a Windows 10 system for me to do that. Patches and merge requests are welcome though.
