### ISSUE TITLE
waveform: supporting string type

### ISSUE THREAD

**Issue by PierreSchnizer** [klemenv/PyDevice#17]
I need to export a list of strings to users I'd like to ask if there are is more interest than only me on that subject.

I have implemented it for ioc based on C so I guess it should be doable for pydev too. I'd like to hear if there is interest in waveform of strings. 

Thanks 
   Pierre

**Comment by klemenv** [comment]
Hi Pierre,
where would you export list of strings to? How would you do that with standard records?

**Comment by klemenv** [comment]
Fixed in recent commit
