### ISSUE TITLE
Missing pycalcRecord.h

### ISSUE THREAD

**Issue by konrad-gajewski** [klemenv/PyDevice#21]
I'm trying to build the module on Centos7, Epics base 7.0.6.1 but the compilation fails due to missing pycalcRecord.h
I can't find this file in the repository.

**Comment by klemenv** [comment]
pycalcRecord.h gets generated from pycalcRecord.dbd by the EPICS build system as part of the project build. It usually ends up in src/O.Common/pycalcRecord.h. If your system fails to locate the file, it may be that it didn't get generated. Is there any other errors in the compiled output? Can you paste it here just to make sure?

**Comment by konrad-gajewski** [comment]
I'm using E3 build system (http://e3.pages.esss.lu.se/) and apparently generation of pycalcRecord.h from pycalcRecord.dbd is missing. I'm not enough competent to fix it but if I new the command to create the header file manually it would help.
Here's the dump of the compilation process:
`(7.0.6.1-4.0.0)[konrad@nuc-07 e3-pydev]$ make build
cd PyDevice && git checkout 32e9fac
HEAD is now at 32e9fac... Support for concurrent record processing
make[1]: Entering directory `/home/konrad/modules/e3-pydev/PyDevice'
make[1]: Nothing to be done for `prebuild'.
make[1]: Leaving directory `/home/konrad/modules/e3-pydev/PyDevice'
make[1]: Entering directory `/home/konrad/modules/e3-pydev/PyDevice'
make[2]: Entering directory `/home/konrad/modules/e3-pydev/PyDevice'
MAKING EPICS VERSION 7.0.6.1
mkdir -p O.7.0.6.1_Common
MAKING ARCH linux-x86_64
make[3]: Entering directory `/home/konrad/modules/e3-pydev/PyDevice'
mkdir -p O.7.0.6.1_linux-x86_64
make[4]: Entering directory `/home/konrad/modules/e3-pydev/PyDevice/O.7.0.6.1_linux-x86_64'
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall              -I/usr/include/python3.6m -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++11  -mtune=generic -std=c++11               -m64 -fPIC          -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c  .././src/util.cpp
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall              -I/usr/include/python3.6m -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++11  -mtune=generic -std=c++11               -m64 -fPIC          -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c  .././src/pywrapper.cpp
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall              -I/usr/include/python3.6m -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++11  -mtune=generic -std=c++11               -m64 -fPIC          -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c  .././src/pydev_waveform.cpp
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall              -I/usr/include/python3.6m -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++11  -mtune=generic -std=c++11               -m64 -fPIC          -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c  .././src/pydev_stringout.cpp
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall              -I/usr/include/python3.6m -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++11  -mtune=generic -std=c++11               -m64 -fPIC          -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c  .././src/pydev_stringin.cpp
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall              -I/usr/include/python3.6m -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++11  -mtune=generic -std=c++11               -m64 -fPIC          -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c  .././src/pydev_mbbo.cpp
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall              -I/usr/include/python3.6m -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++11  -mtune=generic -std=c++11               -m64 -fPIC          -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c  .././src/pydev_mbbi.cpp
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall              -I/usr/include/python3.6m -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++11  -mtune=generic -std=c++11               -m64 -fPIC          -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c  .././src/pydev_lso.cpp
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall              -I/usr/include/python3.6m -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++11  -mtune=generic -std=c++11               -m64 -fPIC          -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c  .././src/pydev_lsi.cpp
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall              -I/usr/include/python3.6m -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++11  -mtune=generic -std=c++11               -m64 -fPIC          -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c  .././src/pydev_longout.cpp
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall              -I/usr/include/python3.6m -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++11  -mtune=generic -std=c++11               -m64 -fPIC          -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c  .././src/pydev_longin.cpp
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall              -I/usr/include/python3.6m -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++11  -mtune=generic -std=c++11               -m64 -fPIC          -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c  .././src/pydev_bo.cpp
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall              -I/usr/include/python3.6m -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++11  -mtune=generic -std=c++11               -m64 -fPIC          -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c  .././src/pydev_bi.cpp
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall              -I/usr/include/python3.6m -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++11  -mtune=generic -std=c++11               -m64 -fPIC          -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c  .././src/pydev_ao.cpp
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall              -I/usr/include/python3.6m -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++11  -mtune=generic -std=c++11               -m64 -fPIC          -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c  .././src/pydev_ai.cpp
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall              -I/usr/include/python3.6m -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++11  -mtune=generic -std=c++11               -m64 -fPIC          -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c  .././src/pycalcRecord.cpp
.././src/pycalcRecord.cpp:32:26: fatal error: pycalcRecord.h: No such file or directory
 #include "pycalcRecord.h"
                          ^
compilation terminated.
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall              -I/usr/include/python3.6m -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++11  -mtune=generic -std=c++11               -m64 -fPIC          -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c  .././src/epicsdevice.cpp
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall              -I/usr/include/python3.6m -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++11  -mtune=generic -std=c++11               -m64 -fPIC          -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c  .././src/asyncexec.cpp
make[4]: Leaving directory `/home/konrad/modules/e3-pydev/PyDevice/O.7.0.6.1_linux-x86_64'
make[4]: Entering directory `/home/konrad/modules/e3-pydev/PyDevice/O.7.0.6.1_linux-x86_64'
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall              -I/usr/include/python3.6m -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++11  -mtune=generic -std=c++11               -m64 -fPIC          -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c  .././src/pycalcRecord.cpp
.././src/pycalcRecord.cpp:32:26: fatal error: pycalcRecord.h: No such file or directory
 #include "pycalcRecord.h"
                          ^
compilation terminated.
Expanding pydev.dbd
/epics/base-7.0.6.1/require/4.0.0/tools/expandDBD.tcl -7.0.6 -I .././src/ -I /epics/base-7.0.6.1/dbd .././src/pydev.dbd .././src/pycalcRecord.dbd > pydev.dbd
perl -CSD /epics/base-7.0.6.1/bin/linux-x86_64/dbdToRecordtypeH.pl  -I .././src/ -I /epics/base-7.0.6.1/dbd  -I. -I.. -I../O.7.0.6.1_Common -I/epics/base-7.0.6.1/require/4.0.0/siteMods/pydev/1.2.0+0/dbd -o pycalcRecord.h .././src/pycalcRecord.dbd
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall              -I/usr/include/python3.6m -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++11  -mtune=generic -std=c++11               -m64 -fPIC          -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c .././src/pycalcRecord.cpp
perl -CSD /epics/base-7.0.6.1/bin/linux-x86_64/registerRecordDeviceDriver.pl pydev.dbd pydev_registerRecordDeviceDriver | grep -v 'iocshRegisterCommon();' > pydev_registerRecordDeviceDriver.cpp
Device 'pydev' refers to unknown record type 'ao'.
Record type 'ao' declared.
Device 'pydev' refers to unknown record type 'longout'.
Record type 'longout' declared.
Device 'pydev' refers to unknown record type 'bo'.
Record type 'bo' declared.
Device 'pydev' refers to unknown record type 'mbbo'.
Record type 'mbbo' declared.
Device 'pydev' refers to unknown record type 'stringout'.
Record type 'stringout' declared.
Device 'pydev' refers to unknown record type 'ai'.
Record type 'ai' declared.
Device 'pydev' refers to unknown record type 'longin'.
Record type 'longin' declared.
Device 'pydev' refers to unknown record type 'bi'.
Record type 'bi' declared.
Device 'pydev' refers to unknown record type 'mbbi'.
Record type 'mbbi' declared.
Device 'pydev' refers to unknown record type 'stringin'.
Record type 'stringin' declared.
Device 'pydev' refers to unknown record type 'waveform'.
Record type 'waveform' declared.
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall              -I/usr/include/python3.6m -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++11  -mtune=generic -std=c++11               -m64 -fPIC          -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c pydev_registerRecordDeviceDriver.cpp
echo "char _pydevLibRelease[] = \"1.2.0+0\";" >> pydev_version_1.2.0+0.c
/usr/bin/gcc  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET            -D_X86_64_  -DUNIX  -Dlinux             -MD   -O3 -g   -Wall -Werror-implicit-function-declaration               -mtune=generic      -m64 -fPIC           -I. -I.././src/ -I../ -I../O.7.0.6.1_Common/                                                                                                                          -I/epics/base-7.0.6.1/include -I/epics/base-7.0.6.1/include/compiler/gcc -I/epics/base-7.0.6.1/include/os/Linux                           -c pydev_version_1.2.0+0.c
Collecting dependencies
rm -f pydev.dep.tmp
cat *.d 2>/dev/null | sed 's/ /\n/g' | grep -v '/epics/base-7.0.6.1/include' | sed -n 's%/epics/base-7.0.6.1/require/4.0.0/siteMods/*\([^/]*\)/\([^/]*\)/.*%\1 \2%p; s%/epics/base-7.0.6.1/require/4.0.0/siteMods/*\([^/]*\)/\([^/]*\)/.*%\1 \2%p' > pydev.dep.tmp
cat pydev.dep.tmp | sort -u >> pydev.dep
/usr/bin/g++ -o libpydev.so -shared -fPIC -Wl,-hlibpydev.so,--enable-new-dtags -L/epics/base-7.0.6.1/require/4.0.0/siteMods/pydev/1.2.0+0/lib/linux-x86_64 -Wl,-rpath,/epics/base-7.0.6.1/require/4.0.0/siteMods/pydev/1.2.0+0/lib/linux-x86_64              -lpthread -ldl -lutil -lm -lpython3.6m -Xlinker -export-dynamic       -rdynamic -m64               -Wl,--defsym,pydevLib_1.0=0 -Wl,--defsym,pydevLib_1.1=0 -Wl,--defsym,pydevLib_1.2=0      asyncexec.o epicsdevice.o pycalcRecord.o pydev_ai.o pydev_ao.o pydev_bi.o pydev_bo.o pydev_longin.o pydev_longout.o pydev_lsi.o pydev_lso.o pydev_mbbi.o pydev_mbbo.o pydev_stringin.o pydev_stringout.o pydev_waveform.o pywrapper.o util.o pydev_registerRecordDeviceDriver.o pydev_version_1.2.0+0.o     -lpython3.6m -lpthread    -lm -lrt -ldl -lgcc
make[4]: Leaving directory `/home/konrad/modules/e3-pydev/PyDevice/O.7.0.6.1_linux-x86_64'
make[3]: Leaving directory `/home/konrad/modules/e3-pydev/PyDevice'
make[2]: Leaving directory `/home/konrad/modules/e3-pydev/PyDevice'
make[1]: Leaving directory `/home/konrad/modules/e3-pydev/PyDevice'
`

**Comment by klemenv** [comment]
Generating of the pycalcRecord.h is actually in your output, just after it's actually needed:

`perl -CSD /epics/base-7.0.6.1/bin/linux-x86_64/dbdToRecordtypeH.pl -I .././src/ -I /epics/base-7.0.6.1/dbd -I. -I.. -I../O.7.0.6.1_Common -I/epics/base-7.0.6.1/require/4.0.0/siteMods/pydev/1.2.0+0/dbd -o pycalcRecord.h .././src/pycalcRecord.dbd
`

I'm wondering if your E3 build system is either re-arranging the Makefile rules, or more likely trying to run in parallel.

**Comment by konrad-gajewski** [comment]
Sorry, I have missed it that pycalcRecord.h is created and pycalcRecord.c is afterwards compiled without any errors. Actually the whole process (compiling, linking and installation of pudev module) was successful. 
The E3 build system doesn't use any of the Makefiles in this repository, so the reported problem was caused entirely by the E3 build system.
I'm closing this issue and will report this problem to the maintainer of E3 build system.
