### ISSUE TITLE
Segmentation fault when stopping demo IOC

### ISSUE THREAD

**Issue by simon-ess** [klemenv/PyDevice#4]
Hello -

I have followed the steps described in the README file, updating PYTHON-CONFIG and EPICS_BASE to suit my install, and I run into the following problem: The IOC starts fine, but when I exit I get a crash:

```
$ ./st.cmd
#!../../bin/linux-x86_64/pydevioc
< envPaths
epicsEnvSet("IOC","iocpydev")
epicsEnvSet("TOP","/home/simonrose/git/PyDevice")
epicsEnvSet("EPICS_BASE","/home/simonrose/git/base-7.0")
# PYTHONPATH points to folders where Python modules are.
epicsEnvSet("PYTHONPATH","/home/simonrose/git/PyDevice/python")
cd /home/simonrose/git/PyDevice
## Register all support components
dbLoadDatabase "/home/simonrose/git/PyDevice/dbd/pydevioc.dbd"
pydevioc_registerRecordDeviceDriver pdbbase
## Load record instances
dbLoadRecords("/home/simonrose/git/PyDevice/db/pydevtest.db")
cd /home/simonrose/git/PyDevice/iocBoot/iocpydev
pydev("import time")
pydev("import pydevtest")
pydev("google = pydevtest.HttpClient('www.google.com', 80)")
iocInit
Starting iocInit
############################################################################
## EPICS R7.0.4.2-DEV
## Rev. R7.0.4.1-152-g4e81eaa7e85c886437a6
############################################################################
iocRun: All initialization complete
epics> exit
Fatal Python error: PyThreadState_Delete: tstate is still current
```

I haven't had that much luck googling the error "PyThreadState_Delete: state is still current". Is this something that you have seen?

The system in question is a CentOS7 system, and I am building against EPICS base 7.0.4.1.

**Comment by klemenv** [comment]
Hi Simon, we've seen this behavior at some of the IOCs we run, I guess it's time to investigate. The crash message we get is consistent with yours, although it was different prior to the Python3 support.

**Comment by klemenv** [comment]
Could you give this patch a shot and test it yourself?

**Comment by simon-ess** [comment]
Seems to have fixed it, yes.
